/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      animation: {
        'blob': 'blob 7s infinite',
        'fade-in': 'fadeIn 0.3s ease-in',
      },
      keyframes: {
        blob: {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)' },
          '25%': { transform: 'translate(20px, -50px) scale(1.1)' },
          '50%': { transform: 'translate(-20px, 20px) scale(0.9)' },
          '75%': { transform: 'translate(50px, 50px) scale(1.05)' },
        },
        fadeIn: {
          from: { opacity: '0', transform: 'translateY(-10px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
  safelist: [
    'from-blue-500',
    'to-blue-700',
    'from-green-500',
    'to-green-700',
    'from-purple-500',
    'to-purple-700',
    'from-orange-500',
    'to-orange-700',
    'from-pink-500',
    'to-pink-700',
    'from-red-500',
    'to-orange-500',
    'from-orange-500',
    'to-yellow-500',
    'from-blue-500',
    'to-cyan-500',
    'from-purple-500',
    'to-pink-500',
    'from-yellow-500',
    'to-green-500',
    'from-green-500',
    'to-emerald-500',
    'text-blue-600',
    'text-green-600',
    'text-purple-600',
    'bg-blue-50',
    'bg-green-50',
    'bg-purple-50',
    'bg-orange-50',
    'bg-pink-50',
    'border-blue-500',
    'border-green-500',
    'border-purple-500',
    'border-orange-500',
    'border-pink-500',
    'from-blue-100',
    'to-blue-200',
    'from-green-100',
    'to-green-200',
    'from-purple-100',
    'to-purple-200',
  ],
}